filename:
    input_file      : "twitter_input"
    target_file     : "twitter_target"
    dialog_file     : "twitter_dialog"
    standard_file   : "standard"
    part_file       : "part"

dump:
    turn_file       : on
    dialog_file     : on
    standard_file   : on
    part_file       : on

filter:
    length:
        len_min         : 6
        len_max         : 36
        sent_len_min    : 4
        sent_len_max    : 24
        sent_min        : 1
        sent_max        : 3
        turn_min        : 1
        turn_max        : 5
        len_diff        : 15
    dump:
        noun            : on
        verb            : on
        adjective       : on
        adverb          : on
        particle        : on
        auxiliary_verb  : on
        conjunction     : on
        prefix          : on
        filler          : on
        impression_verb : on
        three_dots      : on
        phrase_point    : on
        reading_point   : on
        other           : on
    exist:
        noun            : off
        verb            : off
        adjective       : off
        adverb          : off
        particle        : off
        auxiliary_verb  : off
        conjunction     : off
        prefix          : off
        filler          : off
        impression_verb : off
        three_dots      : off
        phrase_point    : off
        reading_point   : off

print_progress: on

part:
    noun            : "名詞"
    verb            : "動詞"
    adjective       : "形容詞"
    adverb          : "副詞"
    particle        : "助詞"
    auxiliary_verb  : "助動詞"
    conjunction     : "接続詞"
    prefix          : "接頭詞"
    filler          : "フィラー"
    impression_verb : "感動詞"
    three_dots      : "ドット"
    phrase_point    : "句点"
    reading_point   : "読点"
    other           : "その他"
