filename:
    input_file      : twitter_input
    target_file     : twitter_target
    dialog_file     : twitter_dialog

dump:
    turn_file       : on
    dialog_file     : on

filter:
    len_min         : 6
    len_max         : 24
    sent_len_min    : 4
    sent_len_max    : 16
    sent_min        : 1
    sent_max        : 3
    turn_min        : 1
    turn_max        : 5
    len_diff        : 10

print:
    progress    : on
